# Generated by Django 6.0.3 on 2026-03-07 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=55)),
                ('position', models.PositiveIntegerField(db_index=True, default=0)),
                ('content', models.TextField(blank=True)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('character_count', models.PositiveIntegerField(default=0)),
                ('last_autosaved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChapterNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField()),
                ('pinned', models.BooleanField(default=False)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='studio.chapter')),
            ],
            options={
                'ordering': ['-pinned', '-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChapterRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('content', models.TextField(blank=True)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('character_count', models.PositiveIntegerField(default=0)),
                ('source', models.CharField(choices=[('autosave', 'Autosave'), ('manual', 'Manual')], default='autosave', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='studio.chapter')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChapterSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('summary', models.TextField(blank=True)),
                ('chapter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='studio.chapter')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pen_name', models.CharField(blank=True, max_length=120)),
                ('bio', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('default_font_family', models.CharField(choices=[('serif', 'Serif'), ('sans', 'Sans'), ('mono', 'Mono')], default='serif', max_length=20)),
                ('default_font_size', models.PositiveSmallIntegerField(default=18)),
                ('default_line_height', models.FloatField(default=1.8)),
                ('default_content_width', models.PositiveSmallIntegerField(default=820)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=55, unique=True)),
                ('logline', models.CharField(blank=True, max_length=240)),
                ('description', models.TextField(blank=True)),
                ('genre', models.CharField(blank=True, max_length=120)),
                ('accent_color', models.CharField(default='#7c6cf2', max_length=7)),
                ('manuscript_font_family', models.CharField(choices=[('serif', 'Serif'), ('sans', 'Sans'), ('mono', 'Mono')], default='serif', max_length=20)),
                ('manuscript_font_size', models.PositiveSmallIntegerField(default=18)),
                ('manuscript_line_height', models.FloatField(default=1.8)),
                ('manuscript_width', models.PositiveSmallIntegerField(default=820)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CharacterClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_classes', to='studio.project')),
            ],
            options={
                'ordering': ['name', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=140)),
                ('role', models.CharField(blank=True, max_length=160)),
                ('summary', models.TextField(blank=True)),
                ('appearance', models.TextField(blank=True)),
                ('goals', models.TextField(blank=True)),
                ('conflicts', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('classes', models.ManyToManyField(blank=True, related_name='characters', to='studio.characterclass')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='studio.project')),
            ],
            options={
                'ordering': ['name', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='studio.project'),
        ),
        migrations.CreateModel(
            name='ProjectDictionaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('term', models.CharField(max_length=120)),
                ('definition', models.TextField()),
                ('usage_notes', models.CharField(blank=True, max_length=240)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dictionary_entries', to='studio.project')),
            ],
            options={
                'ordering': ['term', 'created_at'],
            },
        ),
    ]
