# Generated by Django 6.0.3 on 2026-03-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0003_add_cover_design'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverdesign',
            name='display_mode',
            field=models.CharField(default='artwork', max_length=20),
        ),
        migrations.AlterField(
            model_name='coverdesign',
            name='title_font',
            field=models.CharField(default='Playfair Display, Georgia, serif', max_length=100),
        ),
    ]
