# Generated by Django 5

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0008_coverdesign_custom_cover_coverdesign_editor_mode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="ui_theme",
            field=models.CharField(
                choices=[("system", "Système"), ("light", "Clair"), ("dark", "Sombre")],
                default="system",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="ui_accent",
            field=models.CharField(blank=True, help_text="Couleur d’accent (#RRGGBB). Vide = thème par défaut.", max_length=7),
        ),
    ]
