# Generated by Django 6.0.3 on 2026-03-07 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_entity', models.CharField(max_length=140)),
                ('to_entity', models.CharField(max_length=140)),
                ('relationship', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='studio.project')),
            ],
            options={
                'ordering': ['from_entity', 'to_entity'],
            },
        ),
        migrations.CreateModel(
            name='FrontBackMatter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section_type', models.CharField(choices=[('dedication', 'Dedication'), ('preface', 'Preface'), ('foreword', 'Foreword'), ('prologue', 'Prologue'), ('epilogue', 'Epilogue'), ('afterword', 'Afterword'), ('appendix', 'Appendix'), ('acknowledgments', 'Acknowledgments'), ('author_note', "Author's Note")], max_length=30)),
                ('title', models.CharField(max_length=160)),
                ('content', models.TextField(blank=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='front_back_matter', to='studio.project')),
            ],
            options={
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True)),
                ('significance', models.TextField(blank=True)),
                ('history', models.TextField(blank=True)),
                ('geography', models.TextField(blank=True)),
                ('culture', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='studio.project')),
            ],
            options={
                'ordering': ['name', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('content', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('pinned', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_notes', to='studio.project')),
            ],
            options={
                'ordering': ['-pinned', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WritingGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_word_count', models.PositiveIntegerField(default=50000)),
                ('daily_target', models.PositiveIntegerField(default=1000)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='writing_goal', to='studio.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
