# Generated by Django 6.0.3 on 2026-03-12 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_connection_frontbackmatter_place_researchnote_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('bg_color', models.CharField(default='#1a1a2e', max_length=20)),
                ('title_text', models.CharField(blank=True, max_length=300)),
                ('title_font', models.CharField(default='Georgia, serif', max_length=100)),
                ('title_size', models.PositiveSmallIntegerField(default=48)),
                ('title_color', models.CharField(default='#ffffff', max_length=20)),
                ('subtitle_text', models.CharField(blank=True, max_length=300)),
                ('subtitle_font', models.CharField(default='Arial, sans-serif', max_length=100)),
                ('subtitle_size', models.PositiveSmallIntegerField(default=14)),
                ('subtitle_color', models.CharField(default='#ec5b13', max_length=20)),
                ('author_text', models.CharField(blank=True, max_length=200)),
                ('author_font', models.CharField(default='Arial, sans-serif', max_length=100)),
                ('author_size', models.PositiveSmallIntegerField(default=16)),
                ('author_color', models.CharField(default='#ffffff', max_length=20)),
                ('layers', models.JSONField(blank=True, default=list)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cover_design', to='studio.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
