# Generated by Django 6.0.3 on 2026-03-14 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0007_mapnode_kind_and_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverdesign',
            name='custom_cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers/custom/'),
        ),
        migrations.AddField(
            model_name='coverdesign',
            name='editor_mode',
            field=models.CharField(choices=[('generated', 'Generated'), ('upload', 'Upload')], default='generated', max_length=20),
        ),
        migrations.AddField(
            model_name='coverdesign',
            name='template_id',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
